In [9]:
import numpy as np
import pandas as pd

In [25]:
## Madaline XOR operation
alpha = 0.5
x = np.array([[1.0, 1.0, 1.0], [1.0, -1.0, 1.0], [-1.0, 1.0, 1.0], [-1.0, -1.0, 1.0]])
w = np.array([[0.05, 0.2, 0.3], [0.1, 0.2, 0.15]])
v = np.array([0.5, 0.5, 0.5])
w_diff = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
t = np.array([-1.0, 1.0, 1.0, -1.0])

df = pd.DataFrame(columns=['x1', 'x2', 'x3', 't','z_in1', 'z_in2', 'y_in', 'y', 'w11', 'w21', 'b1', 'w12', 'w22', 'b2'])
for k in range(3):
    for i in range(4):
        z_in1 = x[i].dot(w[0])
        z_in2 = x[i].dot(w[1])
        if(z_in1 >= 0):
            z1 = 1
        else:
            z1 = -1    
        if(z_in2 >= 0):
            z2 = 1
        else:
            z2 = -1    
        y_in = v[0] * z1 + v[1] * z2 + v[2] * 1
        if(y_in >= 0):
            y = 1
        else:
            y = -1
        if(t[i] != y):
            if(t[i] == 1):
                d1 = (z_in1 - 0) * (z_in1 - 0)
                d2 = (z_in2 - 0) * (z_in2 - 0)
                if(d1 < d2):            
                    w_diff[0][0] = alpha * (1 - z_in1) * x[i][0]
                    w_diff[0][1] = alpha * (1 - z_in1) * x[i][1]
                    w_diff[0][2] = alpha * (1 - z_in1) * x[i][2]
                else:
                    w_diff[1][0] = alpha * (1 - z_in2) * x[i][0]
                    w_diff[1][1] = alpha * (1 - z_in2) * x[i][1]
                    w_diff[1][2] = alpha * (1 - z_in2) * x[i][2]                    

            if(t[i] == -1):
                if(z_in1 > 0):            
                    w_diff[0][0] = alpha * (-1 - z_in1) * x[i][0]
                    w_diff[0][1] = alpha * (-1 - z_in1) * x[i][1]
                    w_diff[0][2] = alpha * (-1 - z_in1) * x[i][2]
                if(z_in2 > 0):
                    w_diff[1][0] = alpha * (-1 - z_in2) * x[i][0]
                    w_diff[1][1] = alpha * (-1 - z_in2) * x[i][1]
                    w_diff[1][2] = alpha * (-1 - z_in2) * x[i][2]                    
        
        w[0][0] = w_diff[0][0] + w[0][0]
        w[0][1] = w_diff[0][1] + w[0][1]
        w[0][2] = w_diff[0][2] + w[0][2]

        w[1][0] = w_diff[1][0] + w[1][0]
        w[1][1] = w_diff[1][1] + w[1][1]
        w[1][2] = w_diff[1][2] + w[1][2]
        
        w_diff[0][0] = w_diff[0][1] = w_diff[0][2] = w_diff[1][0] = w_diff[1][1] = w_diff[1][2] = 0.0
        
        df = df.append({'x1': x[i][0], 'x2': x[i][1], 'x3': x[i][2], 't': t[i], 'z_in1': z_in1, 'z_in2': z_in2, 'y_in': y_in, 'y': y, 'w11': w[0][0], 'w21': w[0][1], 'b1': w[0][2], 'w12': w[1][0], 'w22': w[1][1], 'b2': w[1][2]}, ignore_index=True)

In [26]:
df

,x1,x2,x3,t,z_in1,z_in2,y_in,y,w11,w21,b1,w12,w22,b2
0,1.0,1.0,1.0,-1.0,0.550000,0.450000,1.5,1.0,-0.725000,-0.575000,-0.475000,-0.625000,-0.525000,-0.575000
1,1.0,-1.0,1.0,1.0,-0.625000,-0.675000,-0.5,-1.0,0.087500,-1.387500,0.337500,-0.625000,-0.525000,-0.575000
2,-1.0,1.0,1.0,1.0,-1.137500,-0.475000,-0.5,-1.0,0.087500,-1.387500,0.337500,-1.362500,0.212500,0.162500
3,-1.0,-1.0,1.0,-1.0,1.637500,1.312500,1.5,1.0,1.406250,-0.068750,-0.981250,-0.206250,1.368750,-0.993750
4,1.0,1.0,1.0,-1.0,0.356250,0.168750,1.5,1.0,0.728125,-0.746875,-1.659375,-0.790625,0.784375,-1.578125
5,1.0,-1.0,1.0,1.0,-0.184375,-3.153125,-0.5,-1.0,1.320312,-1.339062,-1.067187,-0.790625,0.784375,-1.578125
6,-1.0,1.0,1.0,1.0,-3.726562,-0.003125,-0.5,-1.0,1.320312,-1.339062,-1.067187,-1.292187,1.285938,-1.076563
7,-1.0,-1.0,1.0,-1.0,-1.048438,-1.070313,-0.5,-1.0,1.320312,-1.339062,-1.067187,-1.292187,1.285938,-1.076563
8,1.0,1.0,1.0,-1.0,-1.085937,-1.082812,-0.5,-1.0,1.320312,-1.339062,-1.067187,-1.292187,1.285938,-1.076563
9,1.0,-1.0,1.0,1.0,1.592187,-3.654688,0.5,1.0,1.320312,-1.339062,-1.067187,-1.292187,1.285938,-1.076563
10,-1.0,1.0,1.0,1.0,-3.726562,1.501562,0.5,1.0,1.320312,-1.339062,-1.067187,-1.292187,1.285938,-1.076563
11,-1.0,-1.0,1.0,-1.0,-1.048438,-1.070313,-0.5,-1.0,1.320312,-1.339062,-1.067187,-1.292187,1.285938,-1.076563